name: proejct-ci

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: dependencies
        run: lein deps

      - name: test
        run: lein test

      - name: build-package
        run: lein uberjar

      - name: upload aritifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: target/*-standalone.jar
          retention-days: 5